### PR TITLE
Fixes #179

### LINKED ISSUE #179: Atomic updates not working fully with streams inside other streams
Creating a new issue out this bug that I found when working on #177 

Basically when you have more complicated dependencies that are updated inside other streams, atomic updates break and you get more updates than you would expect.

Issue can be seen in a test case like this:
``` javascript
var result = 0;
stream(1).map(function() {
  stream(0)
    .map(function(val) {
      result += 1;
      return val + 1;
    })
    .map(function(val) {
      result += 1;
      return val + 1;
    });
});
assert.equal(result, 2);
```

The assert fails with the value of 4 (and before the fix for #177 it would fail with the value of 3).

### PR DESCRIPTION
**Pull request by nordfjord**
We were tracking flushing using one variable while there
were in fact two types of flushing `flushingStreamValue`, and `flushingUpdateQueue`. This is now properly represented as two distinct case.

At the end of the updateStream method I've added a check, that if we're not flushingStreamValue and the streams listeners should be updated then we call `s(s.val)` to force that update.

Finally the update queue has been changed a bit. It now holds streams again. But the streams hold updater function arrays.

Hope you have time to review this soon @paldepind

### CODE REVIEW

**Comment by nordfjord** [comment]
I found one more problem with this. We would still see the same problems if we're doing nested streams in a stream body if we were flushing a stream value.

This has been remedied now, and the fix broke the switchLatest module, so I have now updated the switchlatest module such that

1. it depends on takeUntil (there was a lot of copy pasta between them anyway)
2. it drops 1 value from the stream of streams for the end stream.

It seems the switchLatest module only worked because of a bug :joy:

I added some further readability improvements as well.

File: test/index.js [hunk 1]
```diff
@@ -1006,6 +1021,19 @@ describe('stream', function() {
         [], [1, 3, 2], [2, 8, 7, 6], [3, 5, 4]
       ]);
     });
+    it('#179 nested streams atomic update', function() {
```
Comment (paldepind) [inline test/index.js]: Not sure what I feel about issue numbers in the test description. But, we can keep it if you find it useful :smile:

File: lib/index.js [hunk 2]
```diff
@@ -681,22 +705,23 @@ function flushUpdate() {
...
+    updateListeners(s);
+    if (toUpdate.length > 0) flushUpdate();
+    flushingStreamValue = false;
   } else if (inStream === s) {
     markListeners(s, s.listeners);
   } else {
-    toUpdate.push(function() {
-      updateStreamValue(s, n);
-    });
+    updateLaterUsing(updateStreamValue_(n), s);
```
Comment (paldepind) [inline lib/index.js]: What about using `(s) => updateStreamValue(n, s)` instead? It seems a bit simpler and we avoid using the external curry function in the implementation itself.

File: test/index.js (hunk 1 above)
Comment (nordfjord) [reply test/index.js]: I don't have a preference, Removed.

File: lib/index.js (hunk 2 above)
Comment (nordfjord) [reply lib/index.js]: Yeah, I felt like I would have to use it in more places, but didn't notice it was only in a single place. So the curry has been removed.

**Comment by paldepind** [comment]
LGTM! :tada:
